import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <nav className="bg-blue-900 text-white p-4 flex justify-between items-center">
          <a href="/" className="text-xl font-bold">UniSell</a>

          <div className="flex gap-4 text-sm">
            <a href="/sell" className="hover:text-blue-200">Sell Item</a>
            <a href="/subscribe" className="hover:text-blue-200">Subscribe</a>
            <a href="/login" className="hover:text-blue-200">Login</a>
          </div>
        </nav>

        {children}

      </body>
    </html>
  );
}